name: Build Proxmark3 Package

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo \
            python python-bitarray python-pyaudio python-numpy \
            libsndfile bluez bluez-libs gd qt5-base qt5-tools \
            arm-none-eabi-gcc arm-none-eabi-newlib

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build environment
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .

      - name: Extract package name
        id: get_pkgname
        run: |
          source ./PKGBUILD
          echo "pkgname=$pkgname" >> $GITHUB_OUTPUT
          echo "pkgver=$pkgver" >> $GITHUB_OUTPUT
          echo "pkgrel=$pkgrel" >> $GITHUB_OUTPUT

      - name: Build package
        run: |
          sudo -u builder bash -c "makepkg -sf --noconfirm --clean --noprogressbar --nocolor --log --skipchecksums --skippgpcheck"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_pkgname.outputs.pkgname }}-${{ steps.get_pkgname.outputs.pkgver }}-${{ steps.get_pkgname.outputs.pkgrel }}
          path: '*.pkg.tar.zst'
