name: Build Proxmark3 Package

on:
  schedule:
    - cron: '0 5 * * *'  # ogni giorno alle 05:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git sudo

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build environment
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .

      - name: Check for existing package
        id: pkgcheck
        run: |
          sudo -u builder bash -c "makepkg --nobuild --nocolor --noprepare --skipchecksums --skippgpcheck"
          pkgver=$(source ./PKGBUILD && echo ${pkgver})
          pkgrel=$(source ./PKGBUILD && echo ${pkgrel})
          pkgname=$(source ./PKGBUILD && echo ${pkgname})
          arch=$(source ./PKGBUILD && echo ${arch[0]})
          filename=${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst
          echo "Checking for $filename"
          if [ -f "$filename" ]; then
            echo "Package already exists: $filename"
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "No existing package found"
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Build package
        if: steps.pkgcheck.outputs.skip_build == 'false'
        run: |
          sudo -u builder bash -c "makepkg -sf --noconfirm --clean --noprogressbar --nocolor --log --skipchecksums --skippgpcheck"

      - name: Upload artifact
        if: steps.pkgcheck.outputs.skip_build == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: proxmark3-pkg
          path: '*.pkg.tar.zst'
